spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-manager
    username: postgres
    password: 192837465

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    drop-first: true

server:
  port: 8081